import { Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/header/Header'
import Footer from './ui/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-primary ${inter.className} max-w-[1440px] mx-auto`}>
        <div className='md:px-8 lg:px-32 flex flex-row'>
          <div className="basis-5/12 md:hidden h-screen sticky top-0 pt-24">
            <Header/>
          </div>
          <div className="basis-7/12 md:basis-full">
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  )
}
